feat: workflow deployment [blue]

diff --git a/.github/workflows/build_deploy.yml b/.github/workflows/build_deploy.yml
--- a/.github/workflows/build_deploy.yml
+++ b/.github/workflows/build_deploy.yml
@@ -1,4 +1,4 @@
-name: deploy .net app to elastic beanstalk
+name: build and deploy
 
 on:
   workflow_dispatch:
@@ -72,30 +72,31 @@ jobs:
         aws s3 cp app.zip s3://${{ env.APP_SOLUTION_BUCKET }}/app-${{ steps.create_version.outputs.version_label }}.zip
       working-directory: src/app
 
-    - name: Determine the selected environment from commit message
+    - name: Determine the selected environment
       id: determine-env
       run: |
-        # Get the most recent commit message
-        COMMIT_MSG=$(git log -1 --pretty=%B)
-        echo "Commit message: $COMMIT_MSG"
-
-        # Check if the commit message contains [blue] or [green]
-        if [[ "$COMMIT_MSG" == *"[blue]"* ]]; then
-          DEPLOY_ENV_TG="blue"
-          echo "Deploying to Blue environment (from commit message)."
-        elif [[ "$COMMIT_MSG" == *"[green]"* ]]; then
-          DEPLOY_ENV_TG="green"
-          echo "Deploying to Green environment (from commit message)."
+        if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
+          DEPLOY_ENV_TG="${{ github.event.inputs.deploy_environment }}"
+          echo "Triggered by workflow_dispatch. Selected environment: $DEPLOY_ENV_TG"
         else
-          echo "No environment specified in commit message! Please use '[blue]' or '[green]' in the commit message."
-          exit 1
+          COMMIT_MSG=$(git log -1 --pretty=%B)
+          echo "Commit message: $COMMIT_MSG"
+
+          if [[ "$COMMIT_MSG" == *"[blue]"* ]]; then
+            DEPLOY_ENV_TG="blue"
+            echo "Deploying to Blue environment (from commit message)."
+          elif [[ "$COMMIT_MSG" == *"[green]"* ]]; then
+            DEPLOY_ENV_TG="green"
+            echo "Deploying to Green environment (from commit message)."
+          else
+            echo "No environment specified! Use '[blue]' or '[green]' in the commit message."
+            exit 1
+          fi
         fi
 
-        echo "deploy_env_tg=$DEPLOY_ENV_TG" >> $GITHUB_ENV  # Use GITHUB_ENV to pass to next steps
-        echo "deploy_env_tg=$DEPLOY_ENV_TG" >> $GITHUB_OUTPUT  # Make it available to the next job
-        echo "environment specified: $DEPLOY_ENV_TG"
+        echo "deploy_env_tg=$DEPLOY_ENV_TG" >> $GITHUB_ENV
+        echo "deploy_env_tg=$DEPLOY_ENV_TG" >> $GITHUB_OUTPUT
 
-        # Set the corresponding environment
         if [ "$DEPLOY_ENV_TG" == "blue" ]; then
           echo "deploy_env=${ENV_BLUE}" >> $GITHUB_OUTPUT
         elif [ "$DEPLOY_ENV_TG" == "green" ]; then
@@ -104,6 +105,39 @@ jobs:
           echo "Invalid environment specified!"
           exit 1
         fi
+
+    # - name: Determine the selected environment from commit message
+    #   id: determine-env
+    #   run: |
+    #     # Get the most recent commit message
+    #     COMMIT_MSG=$(git log -1 --pretty=%B)
+    #     echo "Commit message: $COMMIT_MSG"
+
+    #     # Check if the commit message contains [blue] or [green]
+    #     if [[ "$COMMIT_MSG" == *"[blue]"* ]]; then
+    #       DEPLOY_ENV_TG="blue"
+    #       echo "Deploying to Blue environment (from commit message)."
+    #     elif [[ "$COMMIT_MSG" == *"[green]"* ]]; then
+    #       DEPLOY_ENV_TG="green"
+    #       echo "Deploying to Green environment (from commit message)."
+    #     else
+    #       echo "No environment specified in commit message! Please use '[blue]' or '[green]' in the commit message."
+    #       exit 1
+    #     fi
+
+    #     echo "deploy_env_tg=$DEPLOY_ENV_TG" >> $GITHUB_ENV  # Use GITHUB_ENV to pass to next steps
+    #     echo "deploy_env_tg=$DEPLOY_ENV_TG" >> $GITHUB_OUTPUT  # Make it available to the next job
+    #     echo "environment specified: $DEPLOY_ENV_TG"
+
+    #     # Set the corresponding environment
+    #     if [ "$DEPLOY_ENV_TG" == "blue" ]; then
+    #       echo "deploy_env=${ENV_BLUE}" >> $GITHUB_OUTPUT
+    #     elif [ "$DEPLOY_ENV_TG" == "green" ]; then
+    #       echo "deploy_env=${ENV_GREEN}" >> $GITHUB_OUTPUT
+    #     else
+    #       echo "Invalid environment specified!"
+    #       exit 1
+    #     fi
 
     - name: Deploy to selected environment
       run: |
@@ -186,21 +220,42 @@ jobs:
       - name: Determine the selected environment from commit message
         id: determine-env
         run: |
-          # Get the most recent commit message
-          COMMIT_MSG=$(git log -1 --pretty=%B)
-          echo "Commit message: $COMMIT_MSG"
-
-          # Check if the commit message contains [blue] or [green]
-          if [[ "$COMMIT_MSG" == *"[blue]"* ]]; then
-            DEPLOY_ENV_TG="blue"
-            echo "Deploying to Blue environment (from commit message)."
-          elif [[ "$COMMIT_MSG" == *"[green]"* ]]; then
-            DEPLOY_ENV_TG="green"
-            echo "Deploying to Green environment (from commit message)."
+          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
+            DEPLOY_ENV_TG="${{ github.event.inputs.deploy_environment }}"
+            echo "Triggered by workflow_dispatch. Selected environment: $DEPLOY_ENV_TG"
           else
-            echo "No environment specified in commit message! Please use '[blue]' or '[green]' in the commit message."
-            exit 1
+            COMMIT_MSG=$(git log -1 --pretty=%B)
+            echo "Commit message: $COMMIT_MSG"
+
+            if [[ "$COMMIT_MSG" == *"[blue]"* ]]; then
+              DEPLOY_ENV_TG="blue"
+              echo "Deploying to Blue environment (from commit message)."
+            elif [[ "$COMMIT_MSG" == *"[green]"* ]]; then
+              DEPLOY_ENV_TG="green"
+              echo "Deploying to Green environment (from commit message)."
+            else
+              echo "No environment specified! use '[blue]' or '[green]' in the commit message."
+              exit 1
+            fi
           fi
+
+          # id: determine-env
+          # run: |
+          #   # Get the most recent commit message
+          #   COMMIT_MSG=$(git log -1 --pretty=%B)
+          #   echo "Commit message: $COMMIT_MSG"
+
+          #   # Check if the commit message contains [blue] or [green]
+          #   if [[ "$COMMIT_MSG" == *"[blue]"* ]]; then
+          #     DEPLOY_ENV_TG="blue"
+          #     echo "Deploying to Blue environment (from commit message)."
+          #   elif [[ "$COMMIT_MSG" == *"[green]"* ]]; then
+          #     DEPLOY_ENV_TG="green"
+          #     echo "Deploying to Green environment (from commit message)."
+          #   else
+          #     echo "No environment specified! use '[blue]' or '[green]' in the commit message."
+          #     exit 1
+          #   fi
 
           # Determine which environment was selected for deployment
           if [ "$DEPLOY_ENV_TG" == "blue" ]; then
